service: git-action-lambda

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-west-1

functions:
  hello:
    handler: src/handler.generateRandomNumber
