service: git-action-lambda

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-1

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb

  addTwoNumbers:
    handler: src/handler.addTwoNumber
    timeout: 60 # seconds
    memorySize: 128 # mb
